name: Automated Data Preprocessing

on:
  push:
    branches: [main]
    paths:
      - "SMSML_Marvin/Eksperimen_SML_Marvin/preprocessing/**"
      - "SMSML_Marvin/Eksperimen_SML_Marvin/telco_churn_raw/**"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Debug
        run: |
          pwd
          find .

      - name: Run preprocessing
        working-directory: SMSML_Marvin/Eksperimen_SML_Marvin/preprocessing
        run: |
          python automate_Marvin.py \
            --input ../telco_churn_raw/telco_churn_raw.csv \
            --output telco_churn_preprocessing

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telco_churn_preprocessing
          path: SMSML_Marvin/Eksperimen_SML_Marvin/preprocessing/telco_churn_preprocessing
